# tools配置
kernel_src_url=https://gitee.com/openeuler/kernel.git

kernel_src_url_proxy=https://proxy/openeuler/kernel.git

kernel_commitID=860874bd1cca5142eb23d123a0aeac7ec9d73d75

kernel_last_commitID=7ccb8a2b6758a5711040e0d3f6152e4ffd3ebb35

kernel_src_branch=openEuler-25.03

kernel_dst_branch=personal/openEuler-25.03

kernel_dst_url=git@gitee.com:pandongang/kernel.git

kernel_project_url=https://gitee.com/api/v5/repos/pandongang/kernel/pulls

kernel_project_token=99ca60a1a66d62067838e70b5295bdac

kernel_mr_server=gitee

#llm参数
api_key=sk-xxx
base_url=https://dashscope.aliyuncs.com/compatible-mode/v1
model_name=qwen3-max-2025-09-23
temperature=0.2
top_p=0.8
timeout=300
max_workers=8

#excel信息
#补丁分析excel输出路径
patch_excel_gen_path=/tmp

#代码分析回合规则
judge_rules="1、是否是安全性修复，如果补丁修复了安全漏洞，通常需要回合，例如CVE漏洞、权限绕过、远程代码执行；2、严重缺陷修复，如果解决了系统崩溃、数据丢失、功能不可用的bug修复，通常需要回合；3、功能性增强或新特性，一般不回合；4、性能优化，一般不回合；5、本补丁修改自身不满足1、2回合条件，但是属于一个整体系列补丁中一环，暂时评估为需要回合，由人工最终评审，但是需要在判断理由中强调原因；6、如果存在前置补丁或后置补丁依赖，需要列出对应依赖补丁commit id"
